[language-server.ltex]
command = "ltex-ls-plus"

[language-server.ltex.config.ltex]
language = "pt-BR"
dictionary."pt-BR" = [
  "Nix",
  "NixOS",
  "Nixpkgs",
  "nixpkgs",
  "DSL",
  "declarativo",
  "reprodutibilidade"
]

[language-server.ltex.config.ltex.latex.commands]
"\\usetheme{}" = "ignore"
"\\usecolortheme{}" = "ignore"
"\\usepackage[]{}" = "ignore"

[[language]]
name = "latex"
language-servers = ["texlab", "ltex"]

[language.soft-wrap]
enable = true
